### ISSUE TITLE
Set up default settings

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP-elixir#1]
I'm seeing this message:
```
:: <-  elixir window/showMessage: {'type': 3, 'message': 'Did not receive workspace/didChangeConfiguration notification after 5 seconds. Using default settings.'}
```
If you set up settings in the `"settings"` entry of LSP-elixir.sublime-settings, they will be sent with `workspace/didChangeConfiguration`. It will allow users to customize them, too.

**Comment by ihabunek** [comment]
Done. Thanks for the report. Had some trouble finding what the settings exist. I'll bring it up with elixir-ls people.

**Comment by rwols** [comment]
Usually what language server maintainers do is to make a list of the settings in their README like this:

```js
"elixirLS.dialyzerEnabled": true,
"elixirLS.dialyzerWarnOpts": [],
"elixirLS.dialyzerFormat": "dialyxir_long"
```
You've turned this path-notation for keys into python dicts, but note that for ST4 you can take these path-notation keys and literally paste them into the `"settings"` dict.

**Comment by ihabunek** [comment]
OK, makes sense to use the dot notation. Is this documented anywhere?

I've chosen the dicts since that's what [all](https://github.com/sublimelsp/LSP-css/blob/master/LSP-css.sublime-settings) [other](https://github.com/sublimelsp/LSP-bash/blob/master/LSP-bash.sublime-settings) [projects](https://github.com/sublimelsp/LSP-intelephense/blob/master/LSP-intelephense.sublime-settings) seem to use.

**Comment by ihabunek** [comment]
@rwols Wait, will the dot notation work in ST3?

**Comment by rwols** [comment]
The dot notation won't work for ST3 :)

**Comment by ihabunek** [comment]
Sigh. :ok_hand:  I'll revert it for now.

**Comment by rwols** [comment]
Also yeah, I'll update the docs about this. There are already examples of this in https://github.com/sublimelsp/LSP/blob/st4000-exploration/docs/index.md (see dockerfile, julia, python). But `"settings"` should have its own section with some clear explanation and examples.

**Comment by ihabunek** [comment]
Thanks for the help, I'll read through that.

It's taking me a long time to get up to speed with sublime package dev. It's not that well documented for 3, let alone 4. That's what you get when you work with closed source I guess.
