### ISSUE TITLE
Elixir-LS 0.5.0

### ISSUE THREAD

**Issue by princemaple** [sublimelsp/LSP-elixir#2]
Hi,

Thanks for the useful little package!

Just a reminder that 0.5.0 was just released.
Also, if you could provide instructions to update, I will send a PR instead next time 😄 

🙏

**Comment by ihabunek** [comment]
Released. Not sure how long it takes for packagecontrol to pick it up.
https://github.com/sublimelsp/LSP-elixir/releases/tag/0.2.0

**Comment by princemaple** [comment]
😍
