### ISSUE TITLE
LSP-elixir cannot start

### ISSUE THREAD

**Issue by dannote** [sublimelsp/LSP-elixir#20]
I get the following exception with the default config on LSP v1.6.1:

`neither "command" nor "tcp_port" is provided; cannot start a language server`

**Comment by cschmatzler** [comment]
Having the same issue on Fedora 34, Sublime 4113 and LSP 1.7.0

**Comment by princemaple** [comment]
0.4.2 might fix it

**Comment by dannote** [comment]
I've added `"command": ["$server_path"]` to my config by hand, and it seems to work now

**Comment by princemaple** [comment]
Thanks for the confirmation
