### ISSUE TITLE
Stopped working after updating to 0.4.5

### ISSUE THREAD

**Issue by optikfluffel** [sublimelsp/LSP-elixir#25]
After the recent update LSP-elixir stopped working entirely for me. No autocompletion, no formatting, no `.elixir-ls` directory in the project folder, nothing. It doesn't even show up in the little menubar at the bottom of Sublime Text. I'm not sure what I've done or if it's running at all. 😅

As far as I know I didn't change anything else on my (M1) Mac.

---
# Troubleshooting: lsp-elixir
## Version
 - LSP: 1.14.0
 - Sublime Text: 4121
## Server Test Run
 - exit code: 0
 - output
```

```
## Server Configuration
 - command
```json
[
  "$server_path"
]
```
 - shell command
```sh
"/Users/username/Library/Caches/Sublime Text/Package Storage/LSP-elixir/server/0.9.0/language_server.sh"
```
 - selector
```

```
 - priority_selector
```
(source.elixir)
```
 - init_options
```json
{}
```
 - settings
```json
{
  "elixirLS": {
    "dialyzerEnabled": true, 
    "dialyzerFormat": "dialyxir_long", 
    "dialyzerWarnOpts": [], 
    "fetchDeps": true, 
    "mixEnv": "test", 
    "mixTarget": null, 
    "projectDir": null
  }
}
```
 - env
```json
{}
```

## Active view
 - File name
```
/Users/username/Desktop/advent_of_code_2021/lib/advent_of_code_2021/day03.ex
```
 - Settings
```json
{
  "auto_complete_selector": "meta.tag, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc", 
  "lsp_active": null, 
  "syntax": "Packages/ElixirSyntax/syntaxes/Elixir.sublime-syntax"
}
```
 - base scope
```
source.elixir
```

## Project / Workspace
 - folders
```json
[
  "/Users/username/Desktop/advent_of_code_2021"
]
```
 - is project: False

## LSP configuration

```json
{}
```
## System PATH
 - /usr/local/bin
 - /usr/bin
 - /bin
 - /usr/sbin
 - /sbin
 - /Library/Apple/usr/bin
 - /Users/username/.asdf/shims
 - /opt/homebrew/opt/asdf/libexec/bin
 - /opt/homebrew/bin
 - /opt/homebrew/sbin
 - /Users/username/.cargo/bin

**Comment by princemaple** [comment]
Hi, assuming you have tried the classic restart/reinstall combo?

I briefly tested after upgrading, it was showing tooltips for me. I did have to restart the editor.

I'm already in bed so any further debugging will have to wait till tomorrow (Australia eastern time). Apologies. If it doesn't work for you, you can remove the installed package, manually clone the package and switch to 0.4.4.

**Comment by rchl** [comment]
I might have broken this with an `lsp_utils` update.

It can be easily fixed by adding `"selector": "source.elixir"` setting in this package's settings or in the meantime in your user settings (`Preferences: LSP-elixir Settings` from the Command Palette).

**Comment by optikfluffel** [comment]
@princemaple Don't worry, sleep tight. And thanks for your work!

@rchl Thanks as well, adding `"selector": "source.elixir"` did indeed fix the issue 🚀
