### ISSUE TITLE
Fail to start lsp elixir

### ISSUE THREAD

**Issue by betososa** [sublimelsp/LSP-elixir#29]
Hey! I am using this project in a manjaro OS, installed elixir via asdf

When I try to start the lsp elixir, i get a pop up window saying "lsp-elixir exited with status code 127"

When looking at the debug panel i see the message
lsp-elixir: ~/.cache/sublime-text/Package Storage/LSP-elixir/server/0.11.0/launch.sh: line 73: exec: elixir: not found

If i run elixir in a termninal, i see that it actually runs, do you know what I am missing?

Thanks!

**Comment by rwols** [comment]
See https://lsp.sublimetext.io/troubleshooting/#updating-the-path-used-by-lsp-servers

**Comment by betososa** [comment]
Thank you so much, it pointed in me the right direction, in the end, what end up solving my issue was tthis

https://github.com/sublimehq/sublime_text/issues/3288#issuecomment-615485720
