### ISSUE TITLE
/launch.sh: line 73: exec: elixir: not found in Mac OS

### ISSUE THREAD

**Issue by freewebwithme** [sublimelsp/LSP-elixir#31]
Hello.
I am trying ton setup Sublime text 4 for elixir.
I installed ElixirSyntax, LSP and LSP - Elixir package
But I got this error
```
lsp-elixir: /Users/myname/Library/Caches/Sublime Text/Package Storage/LSP-elixir/server/0.12.0/launch.sh: line 73: exec: elixir: not found
```
My elixir is in this directory
```
/Users/myname/.asdf/shims/elixir
```

And in Sublime Console, I triged
```
import os;
os.environ["PATH"]

'/Users/myname/.asdf/shims/elixir:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki'

It seems like `elixir` in correct path.

Can you guys help me?
What am I missing here?
Any thought?

**Comment by princemaple** [comment]
Hi, first thing first, have you tried restarting sublime? 😊

**Comment by freewebwithme** [comment]
@princemaple Thanks for the advice, Yes, Of course, I even restart the computer

**Comment by princemaple** [comment]
https://github.com/elixir-lsp/elixir-ls/issues/408 probably this?

**Comment by princemaple** [comment]
https://github.com/elixir-editors/elixir-sublime-syntax/issues/56
