### ISSUE TITLE
LSP-elixir won't start

### ISSUE THREAD

**Issue by sardaukar** [sublimelsp/LSP-elixir#46]
I'm seeing

```
LSP: lsp-elixir crashed (5 / 5 times in the last 180.0 seconds), exit code 1, exception: None
```

In my console window, and running the "language_server.sh" file in the install folder (`/home/sardaukar/.cache/sublime-text/Package Storage/LSP-elixir/server/0.17.1
`) I get:

```
Running /home/sardaukar/.cache/sublime-text/Package Storage/LSP-elixir/server/0.17.1/launch.sh
Preferred shell is fish, launching launch.fish
Looking for ASDF install
ASDF install found in /home/sardaukar/.asdf/asdf.fish, sourcing
Installing ElixirLS release v0.17.1
Running in /home/sardaukar/.cache/sublime-text/Package Storage/LSP-elixir/server/0.17.1
Install complete
No file named /home/sardaukar/.cache/sublime-text/Package
```

Looks like the "no file named" part isn't taking into account spaces, and can't properly work with `/home/sardaukar/.cache/sublime-text/Package Storage`'s name. Where is the "No file named" last call made?

I'm on Sublime 4, build 4152

**Comment by princemaple** [comment]
Did previous versions work for you? If they did, please file an issue against elixir-ls

**Comment by sardaukar** [comment]
If the error is in the Sublime package launcher, won't `elixir-ls` maintainers just bounce me back here?

**Comment by princemaple** [comment]
Our code hasn't changed in a bit. That's why I asked if the previous versions worked for you. If they did, then the problem probably isn't from here.

You can turn on debug logs (check lsp docs) and see it from the lsp log panel, see if the problem comes from the language server, or only in python.

On phone, sorry about the vague instructions!

**Comment by sardaukar** [comment]
I haven't used Sublime in a while, so not sure if the previous version worked. Thanks for the replies, anyway.
